apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 00-worker
spec:
  machineConfigSelector:
    matchExpressions:
      - {key: machineconfiguration.openshift.io/role, operator: In, values: [worker,worker-rt]}
